### ISSUE TITLE
SSL

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeonix.github.io#16]
Shouldn't the website use https instead of http as a pro-privacy project?

**Comment by iamsmooth** [comment]
It's being hosted by GitHub. We have no control over that. There is also no private or individual information of any kind on the site; it is all static text.

**Comment by iamsmooth** [comment]
BTW, GitHub hosting does not support https if using a custom domain name, as noted here: https://help.github.com/articles/securing-your-github-pages-site-with-https/

So we would have to change to separate hosting. This seems not a very useful place to focus effort (including ongoing maintenance) IMO. Others may disagree, and open to those views if someone is willing to do the work (again, including ongoing).

**Comment by fwolfst** [comment]
I am pretty sure https on github.io pages will come in foreseeable future, although its a complex issue to tackle.

I'd like to find the "proper" (as there are many) issue to link from here so that we can see when its done. Best I found is this one:

https://github.com/isaacs/github/issues/156

**Comment by schwagdawg** [comment]
from camthegeek:
https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

Looks like its possible now

**Comment by iamsmooth** [comment]
> If you are using A records, you must update your site’s DNS records with new IP addresses

I will look into making this change ASAP

**Comment by Blitzkrieg000** [comment]
Link for this : https://github.com/aeonix/aeon/pull/67

**Comment by BigslimVdub** [comment]
any update on this @iamsmooth ?

**Comment by BigslimVdub** [comment]
Can you please check this box to force HTTPS for Aeon.cash

<img width="744" alt="enable https" src="https://user-images.githubusercontent.com/30030687/60148018-1339ff00-9795-11e9-8cc0-681d1fef36f9.png">

**Comment by BigslimVdub** [comment]
Https://aeon.cash gives cert error now

**Comment by setuidroot** [comment]
The problem here lies solely with aeon.cash's domain DNS records.  When you go to https://aeon.cash, you get a SSL cert error because it gives out github's SSL certificate.  This is/was an issue with Github, but it appears to be (mostly, albeit poorly) fixed now.

You can see the discrepancies here: https://i.imgur.com/CBcV71l.jpg

nslookup on aeon.cash gives some old github IPs, which load github.com (hince the wrong TLS certificate.)  Github is dumb... they should let you make Let's Encrypt certificates with wildcard subdomain for your domain.  But hey... it's Microsoft, nothing ever works right 🙄.

I think the easiest fix for this is to change aeon.cash's DNS records with the domain registrar (namecheap.)

You need to change aeon.cash DNS records from the A records that point to some github IPs into a CNAME record that points to aeonix.github.io.  Basically aeon.cash DNS records need to be the same as www.aeon.cash DNS records (this can only been done from the registrar: namecheap.)

Once both of the CNAME DNS records are set, then you can go to settings and "Enforce HTTPS" since both the root domain (aeon.cash) and the "www." subdomain will direct to aeonix.github.io (which is where it needs to go for github pages.)

Another option to fix this would be using cloudflare (it's free.)  You would register a new cloudflare account and setup DNS records for www./aeon.cash, during which cloudflare tells you the CF nameservers to switch your domain DNS records to.  Then you go to Namecheap and put in those aforementioned CF nameservers... then www./aeon.cash should work fine, but with a CF TLS certificate.  It's probably easier to just fix the DNS records to work with Github pages and keep the L.E. TLS cert (there's an argument to be made that CF is MiTM a lot of the internet... but it's not a big deal especially since Microsoft hosts the website anyways.)

I found this helpful post on how to fix this issue:

https://stackoverflow.com/a/9123911

I don't know who has access to the domain registrar login... I am happy to fix this myself if I'm given (temp) access to the registrar (and I might need access to this repo to access settings.)  But I get you shouldn't trust me with that info... I wouldn't anyways 🤔.  I offer to do it because I don't want to seem like an ass telling somebody else to do it.  If I could fix it with a PR, I would.  I thought adding aeon.cash to the CNAME file in this repo might fix it.  I made a fork to try and test this, but I got stuck without a real domain name for testing (afraid.org subdomains, github doesn't like, or I probably set it up wrong 🤔.)  However I read someplace that github pages only allows the one domain (no extra subdomains or wildcards, which sucks.)

Also.. I have a dedicated server that I'm renting for the main purpose of running Aeon and Monero nodes.  As such, this server has no website attached to its public IP 🤔.  If the community would be willing to chip in a bit to help me cover the server costs, I would be happy to host the site independent of github.  It has 8 cores, 8GB RAM, 1TB HDD, 1Gbps unmetered bandwidth... it should be enough to host aeon.cash, or maybe too much traffic I don't want to saturate my connection 😂.

I suppose I should ping some people I think have access to the domain registrar @iamsmooth @stoffu ... not to be annoying.  My email box is completely drowned with github emails and I'm rarely on here 🤔.
