### ISSUE TITLE
Hosting mailing list for release announcements?

### ISSUE THREAD

**Issue by stoffu** [aeonix/aeonix.github.io#31]
A mailing list for announcing latest releases similar to https://lists.getmonero.org/postorius/lists/monero-announce.lists.getmonero.org/ would be useful, particularly for exchanges and pools. I'm not skilled in the area of server administration, so  it'd be great if someone in the community can step up.

**Comment by ingvardm** [comment]
This pony likes the idea!

**Comment by shigutso** [comment]
Yes that would be really useful if we want Aeon bigger and in more Exchanges

**Comment by Vaidas737** [comment]
I'll look at this on this weekend, I'll let you know if this what I can do for AEON :heart:

**Comment by stoffu** [comment]
@Vaidas737 
Ping

**Comment by Vaidas737** [comment]
@stoffu 
Sorry didn't found the time, I'll check it on this days.

**Comment by shigutso** [comment]
@Vaidas737 
Ping 2

**Comment by BigslimVdub** [comment]
Honestly if you can compile a list of all, I can just send out reminder mails on release or security patches in bulk. I have no list of those specific addresses.

**Comment by stoffu** [comment]
@BigslimVdub 

That's a good and viable idea. I quickly made up a simple email subscription scheme using Google Forms: https://docs.google.com/forms/d/e/1FAIpQLSci2UitA67N0W_xgSPLlGj6acGnTOtTdDR_ODZwXTHXZsWnCQ/viewform

(I know everyone hates Google, but I think it's fine for the time being.)

I can give the list to you when an announcement is to be made. Does this sound good?

**Comment by BigslimVdub** [comment]
@stoffu 
Yes, that sounds good so long as every needed contact is on that list. I do not know all the contacts that there have been in the past, so I would recommend a PR to the official website to include this linker for exchanges/merchants/integrators to add themselves to the list for mailing for the time being if they come across AEON and want to be on the list. If you can edit the list to add all known contacts that would be a good start. I am unsure who was in charge of housing all the contacts before so if they could chime in that would be awesome!

If everyone agrees maybe @aeon1234 could do a PR for the site since he has been doing most for the website recently.

**Comment by aeon1234** [comment]
sorry, I haven't read this until now.
I will try to do something in the coming days.

**Comment by stoffu** [comment]
@BigslimVdub 
Please let me know the email address you'll be using for sending announcements.

**Comment by BigslimVdub** [comment]
I mailed you. Let me know if it went through

**Comment by stoffu** [comment]
Yes, I updated the subscription page with your email address.

**Comment by BigslimVdub** [comment]
So can we close this now that it is set up with #59 ?

**Comment by stoffu** [comment]
Yes
